version: "2"

services:

  proxy:
    build: ./Proxy
    container_name: nginx
    depends_on:
      - restful
    ports:
      - 80:80
      - 8001:8001

  restful:
    image: restful
    container_name: restful
    build: ./Restful
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - 8080:80
  restful:
    image: restful_game
    container_name: restful_game
    build: ./Test_game_Restful
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    ports:
      - 8070:80
  
